apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: selfsigning-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 0m
  name: {{ .Values.name }}
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.name }}
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Values.name }}-cert
