apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipeline-runs.minion.ponglehub.co.uk
spec:
  group: minion.ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                status:
                  type: string
                  enum: [ PENDING, RUNNING, ERROR, COMPLETE ]
                currentTask:
                  type: string
  scope: Namespaced
  names:
    plural: pipeline-runs
    singular: pipeline-run
    kind: PipelineRun
    shortNames:
    - pr