apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.minion.ponglehub.co.uk
spec:
  group: minion.ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resources:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      trigger:
                        type: boolean
                steps:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      resource:
                        type: string
                      action:
                        type: string
                        enum: [ GET, POST ]
                      path:
                        type: string
                      image:
                        type: string
                      command:
                        type: array
                        items:
                          type: string
                    oneOf:
                      - required: [ resource, action, path ]
                      - required: [ image, command ]
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: Pipeline
    shortNames:
    - pi