apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resources.minion.ponglehub.co.uk
spec:
  group: minion.ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                env:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                secrets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mountPath:
                        type: string
                      keys:
                        type: array
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                            path:
                              type: string
  scope: Namespaced
  names:
    plural: resources
    singular: resource
    kind: Resource
    shortNames:
    - res