apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tasks.minion.ponglehub.co.uk
spec:
  group: minion.ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                pipeline:
                  type: string
                run:
                  type: integer
                image:
                  type: string
                status:
                  type: string
                  enum: [ PENDING, RUNNING, ERROR, COMPLETE ]
  scope: Namespaced
  names:
    plural: tasks
    singular: task
    kind: Task
    shortNames:
    - t