apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: versions.minion.ponglehub.co.uk
spec:
  group: minion.ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resource:
                  type: string
                pipeline:
                  type: string
                version:
                  type: string
  scope: Namespaced
  names:
    plural: versions
    singular: version
    kind: Version
    shortNames:
    - v